site_name: Documentation of Pybiscus

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_headings: true

nav:
  - index.md
  - configuration.md
  - getting_started.md
  - how-to.md
