cid: 1
fabric:
  accelerator: gpu
root_dir: ${oc.env:PWD}
model:
  name: cifar
  config:
    input_shape: 3
    mid_shape: 6
    n_classes: 10
    lr: 0.001
data:
  name: cifar
  config:
    data_dir_train: ${root_dir}/datasets/client1/train/
    data_dir_val: ${root_dir}/datasets/client1/val/
    batch_size: 1
server_adress: server:22222