server:
  init:
    root_dir: ${oc.env:PWD}
    logger:
      class_path: lightning.fabric.loggers.TensorBoardLogger
      init_args:
        root_dir: ${server.init.root_dir}/tensorboard
    conf_strategy:
      name: "fabric"
      config:
        min_fit_clients: 2
    conf_fabric:
      accelerator: cpu
      devices: auto
    conf_model:
      name: cifar
      config:
        input_shape: 3
        mid_shape: 6
        n_classes: 10
        lr: 0.001
    conf_data:
      name: cifar
      config:
        dir_train: None
        dir_val: None
        dir_test: ${server.init.root_dir}/datasets/global_test/
        batch_size: 32
    # weights_path: None
  launch:
    server_adress: "[::]:22222"
    num_rounds: 2
    client_configs:
      - ${server.init.root_dir}/configs/client_1.yml
      - ${server.init.root_dir}/configs/client_2.yml
    save_on_train_end: false
