client:
  init:
    cid: 1
    conf_data:
      name: cifar
      config:
        # dir_train: ${root_dir}/datasets/client1/train/
        # dir_val: ${root_dir}/datasets/client1/val/
        dir_train: /home/mrbourbaki/pybiscus/datasets/client1/train/
        dir_val: /home/mrbourbaki/pybiscus/datasets/client1/val/
        dir_test: None
        batch_size: 32
    conf_model:
      name: cifar
      config:
        input_shape: 3
        mid_shape: 6
        n_classes: 10
        lr: 0.001
    conf_fabric:
      accelerator: cpu
      devices: auto
    pre_train_val: false
  start:
    server_adress: localhost:22222
