name: Tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        # poetry-version: ["1.8.2"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2
      - name: Use UV instead of pip
        run: rye config --set-bool behavior.use-uv=true
      - name: Install dependencies
        run: |
          rye sync --no-lock
      - name: Run the automated tests (for example)
        run: rye run pytest -v
